spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rongmall
      username: root
      password: root
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yr.rongmall.entity

logging:
  level:
    com.yr.rongmall: debug